#!/bin/sh
ACT=".next"
CMD="dmenu.bin"
if [ "`pwd`" != "/usr/local/dmenu" ]; then 
    CMD="dmenu-host.bin"
fi

if ./$CMD; then
    if [ -f "$ACT" ]; then 
		RESULT="`sh ./$ACT`"
		echo $RESULT
        if [ -n $? ] ; then
			echo $?
            sleep 5
        fi
        rm "$ACT"
    fi
else
    sleep 1
fi
