#!/bin/sh
ACT=".next"
CMD="dmenu.bin"
if [ "`pwd`" != "/usr/local/dmenu" ]; then CMD="dmenu-host.bin"; fi

if ./$CMD; then
    if [ -f "$ACT" ]; then 
        sh "$ACT"
        rm "$ACT"
    fi
else
    sleep 5
fi
